---
- name: Setup and Deploy Application
  hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true

    - name: Install Docker (if not already installed)
      apt:
        name: docker.io
        state: present
      when: ansible_distribution != "Darwin"

    - name: Install Minikube
      command: brew install minikube
      when: ansible_distribution == "Darwin"

    - name: Start Minikube
      command: minikube start --driver=docker

    - name: Load Docker image into Minikube
      command: minikube image load my-python-app:latest

    - name: Deploy Kubernetes Deployment
      command: kubectl apply -f /Users/oluwakanyinsolaadebanjo/Documents/data-analytics-app/k8sdeployment.yaml

    - name: Deploy Kubernetes Service
      command: kubectl apply -f /Users/oluwakanyinsolaadebanjo/Documents/data-analytics-app/k8sservice.yaml
