---
- name: Setup and Deploy Application
  hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is installed
      shell: |
        if ! command -v docker &>/dev/null; then
          echo "Docker is not installed. Please install Docker manually on macOS."
          exit 1
        fi
      args:
        executable: /bin/bash

    - name: Install Minikube
      become: false
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
        chmod +x minikube-darwin-arm64
        mv minikube-darwin-arm64 /usr/local/bin/minikube
      args:
        executable: /bin/bash

    - name: Start Minikube
      become: false
      shell: |
        minikube start --driver=docker
      args:
        executable: /bin/bash

    - name: Load Docker image into Minikube
      become: false
      shell: |
        minikube image load my-python-app:latest
      args:
        executable: /bin/bash

    - name: Deploy Kubernetes Deployment
      become: false
      command: kubectl apply -f k8sdeployment.yaml

    - name: Deploy Kubernetes Service
      become: false
      command: kubectl apply -f k8sservice.yaml
